### ISSUE TITLE
Is there a Forseti API ?

### ISSUE THREAD

**Issue by SyCode7** [forseti-security/forseti-security#1086]
I have a question, is there a Forseti API ? Its existence will aid easy integration with other tools. Another option is if there is  a Java client ...maybe someone already built a Java wrapper around it.
Happy to hear any suggestions, feedbacks, possible approaches.
Thanks.

**Comment by blueandgold** [comment]
Hi, I want to follow-up here, to see if the [response given in the email group](https://groups.google.com/a/forsetisecurity.org/d/msg/discuss/-ZWFNGFh-qM/Ea6ysIeGCQAJ) was helpful.  

In essence, forseti 2.0 will have a server component, which exposed via gRPC, but you will have to write a java client (the current client is python).  Would that work for you?  

Alternatively, a lot of data are saved in the cloudsql (mysql) database, which again you can easily write a java client to retrieve.

Otherwise, I would be interested to learn the exact integration you need to do (inventory data, violations, etc), and with which kind of app or tool?
