### ISSUE TITLE
Data Studio Integration with Email Notification

### ISSUE THREAD

**Issue by aviakasurvivor** [forseti-security/forseti-security#1126]
@joecheuk  @blueandgold 
Hi,

I am stuck on a particular dashboard creation which is somewhat a replica of Email Sent via SendGrid, can you help me by pointing out the correct table in Google Cloud SQL to which should I point it to and if there are multiple tables being created, how should I map them to one Data Studio Project.
The data generated in the csv file changes the resource_id from integer to 8.39E+11 which breaks the data studio table.

Thanks
Avi

**Comment by blueandgold** [comment]
Hi Avi, can you please be more specific, regarding which email you are tryig to work with?  Is it inventory, scanner, or violations email?  Then, I can point you to the exact tables.

Most likely, multiple tables will be involved.  I have not tried to write sql queries for them nor used Datastudio, so you will have to try it yourself.  I recommend that you hookup a SQL GUI tool (e.g. mysql workbench) so that you can see the inventory & violation tables that you are working with, and also for testing the sql queries.

**Comment by aviakasurvivor** [comment]
Hi @blueandgold ,
I want to create dashboards for every component in Forseti i.e. Inventory, Scanner, and Violation Emails.
If you can help me by pointing to the correct table details for all, it would definitely solve my purpose.

I have created a dashboard for violations in data Studio using the output for Scanner Results present in Google Cloud Storage. I specified a new bucket for the same in the forseti_conf.yaml file and hence was able to use that bucket for data studio.
One thing that caught my eye is the first column resource_id converted the integer value of my project id to something like 4.92E+11 automatically which caused error in data studio and I had to manually format those shells each time.

Since every component is stored in CloudSQL, it would be great if the details can be provided by you, looking forward to hear from you soon.
Thanks,
Avi

**Comment by blueandgold** [comment]
Hi Avi, do you have access to the CloudSQL instance that Forseti sets up?

If you connect to the CloudSQL instance, you can connect to the `forseti_security` database, and there you will see all the tables for the inventory and violations.  Do you see them?  

![image](https://user-images.githubusercontent.com/6977544/36651968-bbfcf0a6-1a60-11e8-8dbf-b0621c14d795.png)

Keep in mind that new tables for each resource & violation are created each time that forseti runs.  

In 2.0, we will consolidate them the one tables.  i.e. each snapshot will add more data to the same table, rather than create new tables.
