### ISSUE TITLE
Investigate and determine the best docker base image to use for CI/CD purposes

### ISSUE THREAD

**Issue by mirons-google** [forseti-security/forseti-security#1429]
Today we use Ubuntu:16.04 which is very large, Docker [recommends](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#the-dockerfile-instructions) using alpine as it's only 5m and will speed up builds and testing.

https://hub.docker.com/_/alpine/

**Comment by blueandgold** [comment]
Today we use Ubuntu 18.04.

**Comment by jceresini** [comment]
I don't agree with using alpine for the forseti docker images. The alpine image ends up needing to compile a number of the python packages, rather than installing the wheels, so first off you bloat the image with a c++ build environment. It also means it takes significantly longer to build the docker images.

As a kind-of experiment, I attempted to create an image that contains all of the python dependencies (from the setup.py file included with forseti), using 3 different base images (The python2 image based on alpine, the python2 image based on debian:slim-stretch, and the ubuntu:18.04 image). This isn't the most scientific (nor the most complete) experiment, but I thought it would be sufficient to demonstrate my point. 

## Tests

First I tried the python2 image based on alpine (python:2-alpine). The dockerfile is shown here, and contains what I believe to be the minimum requirements for installing all of the required python packages in the forseti `setup.py` file.

```
FROM python:2-alpine
COPY required_packages.txt /req.txt
RUN apk add --no-cache mariadb-connector-c-dev libffi-dev g++ #linux-headers openssl-dev
RUN pip install -r /req.txt
```

The image was built on my laptop using the following command: `time docker build --no-cache -t alpine-forseti-requirements -f Dockerfile-alpine .`
This took 9m39s to build and resulting in a 449MB image.

---

Next I tried the python2 image based on debian:slim-stretch (python:2-slim-stretch) with the following Dockerfile

```
FROM python:2-slim-stretch
COPY required_packages.txt /req.txt
RUN apt-get update \
    && apt-get install -y autoconf gcc python-mysqldb \
    && rm -rf /var/lib/apt/lists/*
RUN pip install -r /req.txt
```

Again built on my laptop: `time docker build --no-cache -t debian-forseti-requirements -f Dockerfile-debian-slim .`

Resulting image is 540MB and took 1m25s to build

---

And finally i tried the ubuntu:18.04 image (which ubuntu announced was a new *minimal* ubuntu image https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released). Dockerfile is very similar to the one above but I needed to install python:

```
FROM ubuntu:18.04
COPY required_packages.txt /req.txt
RUN apt-get update \
    && apt-get install -y autoconf gcc python-mysqldb python-pip python-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install -r /req.txt
```

Same build environment: `time docker build --no-cache -t ubuntu-forseti-requirements -f Dockerfile-ubuntu-18.04 .`

Resulting image is 651MB and it took 2m14s to build

## Results

Using the alpine-based python image took nearly 10 minutes, versus 2-3 minutes. The image sizes are fairly close in size. Personally, I use the python:slim-stretch images for python containers as a result of doing similar tests with our applications

python:2-alpine - 9m39s to build - 449MB image size
python:2-slim-stretch - 1m25s to build - 540MB image size
ubuntu:18.04 - 2m42s to build - 651MB image size

There are lots of things to consider when choosing a base image, I just don't think the decision should be based on a docker recommendation that only takes the initial base image size into consideration.

**Comment by jceresini** [comment]
I also submitted PR #1883 to provide a minor decrease in docker image size
