### ISSUE TITLE
Support for Kubernetes

### ISSUE THREAD

**Issue by hypery2k** [forseti-security/forseti-security#1470]
Is it planned to support a pure k8s deployment?

**Comment by victorvess** [comment]
I've actually done some work of my own to get 1.x and 2.0RC1 to run in Kubernetes.  It's working, sorta, but nothing that is fit to contribute back yet.

My $.02: 

- Issue #223 might be a dupe of this, in that the discussion was heading more toward k8s.  The security concerns voiced in that issue are pretty valid.  My team runs an "adminstrative" k8s cluster that is already doing other org privileged things, so that hasn't been a big worry for me.

- I think Issue #1396 needs to have some kind of solution, ideally, to make good progress here.  In Forseti 1.x, I was able to structure the runs as a "cronjob" in k8s and it worked fine.  With the redesign in 2.0, my approach is to get the server running as a "deployment" (i.e. normal pod/service), and the client scripts running as a "cronjob" in k8s.  But the server has no mechanism to formally detect changes in configuration, so either an API trigger or config watcher needs to be in place.

Also just a question on your expectations, since I've gone back and forth on this one as well:  When you say "pure" k8s deployment, are you talking about running the MySQL instance as a pod as well?  Or Cloud SQL with all of the other runtime components in k8s?

**Comment by blueandgold** [comment]
@MartenvanWezel will be the assignee here to connect the right people to work on this.

**Comment by hypery2k** [comment]
yes i mean with pure all within kubernetes, also mysql. I though using a watcher like [kubewatch](https://github.com/bitnami-labs/kubewatch) could be an idea. I would also help on implementation for this and try it out.

**Comment by jjawad-google** [comment]
@hypery2k work on this feature is currently underway for GKE.

**Comment by Red-Five** [comment]
Ref https://github.com/GoogleCloudPlatform/forseti-security/issues/2162
for instructions on deploying proof of concept to GKE.

**Comment by ryanismert** [comment]
Henry is this assigned correctly and still on track for 2.13?

Ryan

**Comment by Red-Five** [comment]
When is 2.13 target release date? 

Main remaining items:

- docker image self contained crontab for long running server
- Tidy up files, add standard copyright/licence header.
- Make deployment easier.
- **Peer review the whole approach and code**

**Comment by blueandgold** [comment]
2.13 release is scheduled for 3/14 (thursday).  @andreyk-code has accepted to review PR #2335 and #2582.

**Comment by Red-Five** [comment]
@ryanismert The basics are all in place now. 

Once code merged and released would welcome user feedback and/or enhancements to the code or deployment approach.

**Comment by mirons-google** [comment]
*Grooming update*: @Red-Five can you respond back with the completion status of this issue?

**Comment by Red-Five** [comment]
> _Grooming update_: @Red-Five can you respond back with the completion status of this issue?

@mirons-google 
The basic PoC is complete. There are always more things that can be done though :slightly_smiling_face:

E.g. container runs as root, need to remove this requirement.
Use config map for env vars.
Offer a push button deployment on an 'opinionated' hardened GKE environment.
Happy to answer any questions...

**Comment by kevensen** [comment]
An update here, the alpha is going out with Forseti 2.19.  I'll wait to that happens, then close this issue, but continue tracking in #2084.  If there are further thoughts, please share.

**Comment by kevensen** [comment]
Closing issue.  Please re-open if further discussion is required.  Otherwise we will track with #2084.
