### ISSUE TITLE
Make the iter method namings consistent.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1901]
We have some method names inventory/base/gcp.py below that have inconsistent namings that is confusing during code review.

Some are `iter_computefirewalls()` style.
Others are `iter_networks()` style.

Please consult with @ahoying on which one is preferred.

https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/google/cloud/forseti/services/inventory/base/gcp.py#L534-L572

**Comment by jceresini** [comment]
Its worth mentioning that across APIs there may be overlap in resource types. As an example, both the compute API and the sql API have instances (`kind` is `compute#instance` and `sql#instance` respectively). Personally, I think it would be nice to adopt the `kind` parameter returned by most of the google APIs instead of the sometimes arbitrary `type` in the forseti database. With the example above, the type for `compute#instance` is `instance` and the type for `sql#instance` is `cloudsqlinstance`

**Comment by blueandgold** [comment]
@jceresini great comment.  So if that's the case, would this be better for disambiguation purpose?
`computeinstance`
`cloudsqlinstance`

**Comment by jceresini** [comment]
If it were up to me, I'd probably use the format `iter_[api]_[res_type]` (with the extra separator) for those functions, since they are defined in a package that is not api-specific. So `iter_compute_instances`, `iter_compute_disks`, `iter_sql_instances` ...

I don't believe there's enough overlapping resource types (just the instances that i can think of off the top of my head) for it to matter much at this time; so I don't have any strong feelings about it.
