### ISSUE TITLE
Update Travis to Build/Test for External Contributors without Access to Encrypted Values

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1913]
In https://github.com/GoogleCloudPlatform/forseti-security/pull/1912, an external contributor submitted a doc change, and ran into Travis error.

https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/418284170?utm_source=github_status&utm_medium=notification

![image](https://user-images.githubusercontent.com/6977544/44350289-cfc78380-a453-11e8-88ca-1cb24d260de0.png)

**Comment by mirons-google** [comment]
This is intentional because only people explicitly added to the repo with privileges will Travis then allow the encrypted values to be decrypted. 

This is for security reasons, more can be read [here](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions).

The Travis configuration file could be tweaked to detect a fork/PR from a non-repo user, that shouldn't have access to the encrypted credentials, to still build/test.

**Comment by blueandgold** [comment]
Thanks for clarifying.... updated the issue to reflect what's happening.

**Comment by dekuhn** [comment]
I tested and the website build with Travis today can work for external contributions. I believe the changes added to test for secure and unsecure variables  addresses this problem.

https://github.com/forseti-security/forseti-security/blob/83275a92f67419cdf855137dca14a4ecf9d45906/.travis.yml#L21

However when I tested this theory I found that the build would timeout on
https://github.com/forseti-security/forseti-security/blob/83275a92f67419cdf855137dca14a4ecf9d45906/.travis.yml#L22 running without secure variables which is the build process ran when submitting a PR.

**Comment by dekuhn** [comment]
The website builds fine now with external contribution. I tested with this PR #3082 https://travis-ci.org/forseti-security/forseti-security/builds/572105858

However I found the build would timeout on:
https://github.com/forseti-security/forseti-security/blob/83275a92f67419cdf855137dca14a4ecf9d45906/.travis.yml#L22

Adding travis_wait in PR #3086 to address this issue.
