### ISSUE TITLE
Avoid throwing key decryption error for PRs from external contributors.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#1997]
Currently, when external contributors submit PRs for documentation changes, Travis will fail with the following errors.

```
The command "openssl aes-256-cbc -K $encrypted_5d3a31857ace_key -iv $encrypted_5d3a31857ace_iv -in client-secrets.json.enc -out client-secrets.json -d" failed and exited with 1 during .
```

https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/425522546?utm_source=github_status&utm_medium=notification

There should be a way to catch this, and handle it better without having to fail Travis.

**Comment by blueandgold** [comment]
The key in question is used for deploying a new appengine version.  If this deployment is happening when someone just want to make a doc change, then we should uncouple this.

**Comment by dekuhn** [comment]
Looks like the Travis config has been updated since this bug was opened, it is skipping the deploy and before_deploy which does the decryption:
- openssl aes-256-cbc -K $encrypted_5d3a31857ace_key -iv $encrypted_5d3a31857ace_iv -in client-secrets.json.enc -out client-secrets.json -d

I just submitted a PR as outside contributor and the Travis build timed out twice, but no error related to the decryption. 

Travis log:
https://travis-ci.org/forseti-security/forseti-security/jobs/571518723
