### ISSUE TITLE
Question/Feature: scan for resources without defined organization labels

### ISSUE THREAD

**Issue by daveresbk** [forseti-security/forseti-security#2000]
Question: I have read your docs, but I don't see any info about scan for resources without defined organization labels. Is it possible? If not, I think it could be an interesting feature.

**Comment by blueandgold** [comment]
@daveresbk Thanks for bringing this up!  Yes, it definitely is possible to audit for labels in various resources (or even tags of resources), and will require adding new scanners.  Which resource labels/tags are you most interested in?

This relates to #864, where we are considering to handle the auditing of resource attributes more generically, so that it's easy to audit the label/tag attributes across many resources.

**Comment by daveresbk** [comment]
Thanks a lot for your reply. 
We set an internal policy to label all resources with the following tags:

- <company>-service | service to which the service belongs
- <company>-project | identify the project the resource supports
- <company>-cluster | if it belongs to a cluster
- <company>-customer | customer to which the service belongs
- <company>-environment | environmentdev - developmentsta - stagingpro - production
- <company>-costcenter | customer that pays this resource (SAP code)
- <company>-version | version of the component (build version) → if no version: "latest"
- <company>-dc | datacenter where the component runs

We are planning to use in all resources but mainly in compute and storage.

Regards,

**Comment by blueandgold** [comment]
The upcoming Scanner 2.0 will have an evaluation engine that will handle resource attributes generically, and so will be able to support this.  Will update this issue when Scanner 2.0 is ready for you to test.  Thanks.
