### ISSUE TITLE
Deploying Forseti on GKE

### ISSUE THREAD

**Issue by rllin-fathom** [forseti-security/forseti-security#2084]
Any plans to move Forseti over to a GKE deployment?

**Benefits**
1. More ephemeral, server/client scale up and down as dictated by a `CronJob` (cheaper and more resilient)
2. Easier to upgrade Forseti (baked into image)
3. Easier to update rules (baked into image)

**Sticky points**
1. permissions and security surrounding use of external GCP resources (e.g. CloudSQL)
2. OR standing up database in GKE

**Comment by Red-Five** [comment]
@rllin-fathom 
Cloud SQL supports internal IP (beta). I have verified that Forseti (v2.5.0) works on GCE with internal IP's end-to-end.
There  is a new Cloud NAT (beta) solution for internet egress from private IP VM's for updates etc.

(Re Docker / GKE: I'm also looking to see if their is a documented list of known issues that need to be resolved.) There is a 'dockerize' branch in git but I don't yet know how far the community got with it.

**Comment by jjawad-google** [comment]
Internally we have a proof of concept and will post here soon.

**Comment by Red-Five** [comment]
> Internally we have a proof of concept and will post here soon.

@jjawad-google Is their any update on this? (If not I hope to get some time to try soon.)

Im guessing steps are
1. Include Google SDK in Forseti image for GCS access.
2. Include Cloud SQL Proxy Side Car for Cloud SQL access
3. Ensure Forseti Service account accessible from Forseti container for GCS access
4. Ensure Forseti Service account accesible from sql side car for SQL access.

**Comment by blueandgold** [comment]
@Red-Five , @angelsungoogle is exploring our options for moving to kubernetes. She will reach out to you to possibly collaborate on this.

**Comment by Red-Five** [comment]
Draft for initial proof of concept. Runs Forseti Server on cos and k8s. (cronjob pending).

https://github.com/GoogleCloudPlatform/forseti-security/pull/2344

**Comment by angelsungoogle** [comment]
Please refer to the [docker-poc](https://github.com/GoogleCloudPlatform/forseti-security/tree/docker-poc) branch for experimental code, and feel free to contribute

**Comment by Red-Five** [comment]
Ref #2162
for instructions on deploying proof of concept to GKE.

**Comment by dekuhn** [comment]
In this quarter we want to flush out a formal design for supporting Forseti on GKE. We plan to use this issue for tracking the work.

We will review and  incorporate  the feedback from these other GKE/K8S/Containerize related github issues: 
Dockerize Forseti (#223)
Support for Kubernetes (#1470)
GKE Kubernetes Deployment PoC Notes (#2162)
k8s Deployment Enhancements (#2626)

**Comment by Red-Five** [comment]
For developers

https://cloud.google.com/cloud-code/ 

https://techcrunch.com/2019/04/10/google-launches-cloud-code-to-make-cloud-native-development-easier/

**Comment by RexBelli** [comment]
I've recently done some work on dockerizing Forseti and running it on GKE (Deployment+CronJob).  I'm not sure how best to integrate this with existing initiatives, or even if it makes sense to, but figured I'd share nonetheless.

Dockerfile: https://github.com/RexBelli/forseti-stuff/tree/master/docker
GKE Setup: https://github.com/RexBelli/forseti-stuff/tree/master/k8s

**Comment by Red-Five** [comment]
@RexBelli Thankyou.

Two approaches here, start from a blank slate using lessons learned
or iterate on existing k8s code. 

I believe some people are already experimenting with the existing k8s code.
Based on your experiences do you have thoughts on iterative changes to the existing code?

-What base image to use?
-Modifying example install script to account for different scenarios?
-Should the config file and rule file contents be loaded into a ConfigMap?

The original code was written by me whilst learning both Forseti and K8S so their may well be
better ways of doing things. In particular I did not use ConfigMap because at that time I didn't know about it : )

**Comment by Red-Five** [comment]
@dekuhn Another item to track
https://github.com/forseti-security/forseti-security/issues/2520

**Comment by Red-Five** [comment]
If anyone interested in a way to use Google Cloud Code with VS Code to develop forseti code, continuously deploy to GKE, remote debug in pods and performance profile I have some draft notes here.

https://github.com/Red-Five/google-cloud-code-forseti-security/wiki

If the community is interested in standardizing on Google Cloud Code with VS Code as an IDE, some of the changes needed could be incorporated into the dev branch (with flags to turn them on-off)

**Comment by blueandgold** [comment]
@RexBelli, we are very interested to have your contribution and expertise to move this POC forward.  @dekuhn will reach out to loop you into our project planning.  Thanks!

@kevensen @hshin-g for FYI

**Comment by RexBelli** [comment]
@blueandgold Awesome!  I'm happy to help any way I can.

@Red-Five 
On building the container, it would be awesome to use something like `scratch` or one of the distroless (https://github.com/GoogleContainerTools/distroless).  I tried to use `gcr.io/distroless/python2.7` by building the dependencies in a build container and then moving everything over to distroless, but I couldn't get it to work.  I don't know a whole lot about the Python dependency model, so someone more knowledgeable might be successful.  Alternatively, if there's a way to build a static ELF binary of Forseti, it could be put into `scratch`.

On installation methods, maybe extend the script to create all its own resources and allow certain pieces to already exist?  The problem I ran into was the script expected to be executed in a project that had already been setup by the standard install process, but the standard install process failed in my environment because I manage my own network (the `default` network was deleted).  Since all you really need from the standard install process is:
- Cloud SQL database
- Service Account with correct permissions
- GCS bucket

these could be provisioned by the script or accept values from stdin.

On config/rules files as ConfigMaps, like you, I used those because it's what I know. :smiley:  Thinking back, it probably makes more sense to keep rules files in a GCS bucket.  However, due to the flexibility of Forseti, that's an option that can be left up to the user!

**Comment by kevensen** [comment]
I think as far as deployment we ought to look at helm.  I've created some charts to orchestrate the deployment.  I'll share those as soon as we get a repo in the Forseti org for helm.

With the image, as small as possible is key.  @RexBelli I like the idea of gcr.io/distroless/python2.7.  I've had success with python:2.7.16-slim.

As far as keeping the files in the GCS bucket, I tend to agree.  That being said we ought to avoid installing any utilities in a container that we don't need.  We may want to look at a Kubernetes operator that watches for change events on the bucket, then updates configmaps in the cluster.

**Comment by RexBelli** [comment]
@kevensen I agree on Helm, though, If possible, a Tiller-less approach should be used.

> We may want to look at a Kubernetes operator that watches for change events on the bucket, then updates configmaps in the cluster.

I might be misunderstanding, but why use both a configmap and a GCS bucket?  Since Forseti can pull from GCS directly, it seems you could remove the configmap entirely.

**Comment by kevensen** [comment]
Fortunately the option to not use Tiller is inherently available.

Can you please help me understand how the Forseti server container, for example, would pull in it's config and rules?  Programmatically?

**Comment by RexBelli** [comment]
> Fortunately the option to not use Tiller is inherently available.

Nice!  I wasn't aware that was possible yet with stock Helm.

> Can you please help me understand how the Forseti server container, for example, would pull in it's config and rules? Programmatically?

Ah, the confusion may lie in the config file.  I was referring to the rules only, which, AFAICT, can be pulled directly from GCS: https://github.com/forseti-security/forseti-security/blob/dev/configs/server/forseti_conf_server.yaml.in#L200

**Comment by kevensen** [comment]
@RexBelli RE: rules, that will make things simple!  How to obtain the config file will need some thought.  I am open to ideas.

**Comment by Red-Five** [comment]
Re rules and config: the existing PoC is fully functional (gsutil cp is used). I wouldn't get too hung up on configs at this point. 

There are some minor (in terms of time) security issues to address.
1. Remove need to run container as root to use gsutil (easy fix)
2. PoC use of KMS to protect the secret.

The main thing for the initial 'list and shift' is to make it easy to deploy.

Then we need advice from folks familiar with the code on how to take advantage of horizontal scaling.
What (micro) services make sense? (e.g. inventory performance issues.)

I also suspect the config validator may be able to completely replace much of the existing python scanners once
it has enough rules built for it; so need to understand how best to use cv in k8s (assume a separate container with service in front)

**Comment by dekuhn** [comment]
Linking here the Requirements and Design doc the team is collaborating on:
[Requirements/User Stories](https://docs.google.com/document/d/1HSR0IxgivoaCdAyTVM2vpNu-6tXm7eGg9RYRtEHKjhQ/)
[Forseti on GKE Design](https://docs.google.com/document/d/1EmFjjGzVcILb143q3ZTSigjMOR-_3TliNOM7lq-y17)

**Comment by gkowalski-google** [comment]
Forseti can be deployed to GKE by following the website instructions here: https://forsetisecurity.org/docs/latest/setup/forseti-on-gke.html.
