### ISSUE TITLE
Dockerize Forseti

### ISSUE THREAD

**Issue by carise** [forseti-security/forseti-security#223]

**Comment by blueandgold** [comment]
A part of this issue is to help developers setup forseti for them to tweak or contribute.  So, we need to see how to hook up Eclipse (or other IDEs) to the forseti code inside the docker image.

**Comment by carise** [comment]
Dockerfile is complete, just need to publish documentation. I have something written up for "experimental use".

**Comment by carise** [comment]
Progress here: https://github.com/GoogleCloudPlatform/forseti-security/tree/dockerize

**Comment by bt3gl** [comment]
Hi all,
I'm working on deploying forseti with kubernetes and I was wondering what's missing for this issue to be closed? I could be able to help as well.

Thank you!

**Comment by blueandgold** [comment]
We have not made more progress here, other than make forseti runnable as a docker container.  If you can make this run on kubernetes, we would love to learn anything that you do: configuration, permission, etc.

**Comment by Glennvd** [comment]
Would anything other than mounting your service account as a secret be needed to make this workable on a Kubernetes engine setup? The hard part would be writing the security policies to control who would be able to access the Forseti namespace (and thus organisational service account). 
For that reason alone I'd prefer to run forseti on a dedicated VM in a separate project rather than on a kubernetes cluster.

**Comment by blueandgold** [comment]
@bt3gl, would you be able to address @Glennvd's question on managing access to Forseti on kubernetes?

**Comment by dekuhn** [comment]
Marking as dupe of #2084
