### ISSUE TITLE
Audit Log Scanner Giving Wrong Violations

### ISSUE THREAD

**Issue by hariram01** [forseti-security/forseti-security#2786]
Hi

I am using forseti V2.14 in my project.

I having issue in Scanner. When i am trying to run Audit Log Scanner it is wrongly reporting violations for all services which all service Log type enable.

I am deployed forseti via local system .Please find attached error and screen of the screen.

[Audit Log Scanner Bug.xlsx](https://github.com/forseti-security/forseti-security/files/3134703/Audit.Log.Scanner.Bug.xlsx)
![Audit Log Scanner](https://user-images.githubusercontent.com/50173659/57020706-28146f00-6bf8-11e9-874c-bffa172fe249.PNG)

Thanks!
Hari

**Comment by red2k18** [comment]
Size 1 as it needs to be investigated.

**Comment by red2k18** [comment]
Hi, are you still seeing this issue? If so, could you share with us the rule you configured for this?

**Comment by hariram01** [comment]
Hi,
Should l updated the forseti release ?

**Comment by red2k18** [comment]
I'm not sure what you mean. Could you please rephrase?

**Comment by hariram01** [comment]
Hi
I tested on release V2.14.0. So should I update forseti release to test it?

**Comment by red2k18** [comment]
Hi, is it working on v2.13.0? Yes, we recommend to update as soon as the new version is released. We're on v2.16.0

**Comment by red2k18** [comment]
Also, is it possible for you to share with us the rule you have configured for this?

**Comment by hshin-g** [comment]
Forseti Engineering team will try to reproduce this issue.

**Comment by blueandgold** [comment]
@hariram01, I am able to reproduce this issue, and confirms that this is a problem.

I am going to assume that you are using cloud asset inventory (CAI) to build the inventory data (this is the default option).  So, the problem is that the audit log data provided by CAI is differing from the data provided via the API call. (Please see the screenshot below)

So, for example, you can see the key names are different (`auditConfigs` vs `audit_configs`) or (`ADMIN_READ` vs `1`). 

![image](https://user-images.githubusercontent.com/6977544/61426510-79ff9380-a8cf-11e9-9426-74621d4a51ee.png)

The CAI team will be fixing this soon on their end, and when they do, this will be resolved.  I will keep this issue open and assigned to me to verify and then will let know via update in this issue.

Thanks.

**Comment by hshin-g** [comment]
This issue has been resolved. The audit log violations are being reported.
