### ISSUE TITLE
Inventory depends on certain google apis to be enabled while CAI can support those resources w/o enabling those APIs. 

### ISSUE THREAD

**Issue by joecheuk** [forseti-security/forseti-security#2897]
e.g. to inventory GCS bucket, we first check and see if storage API is enabled :-

```
def storage_api_enabled(self):
"""whether storage api is enabled.

Returns:
bool: if this API service is enabled on the project.
"""
return self.is_api_enabled('storage-component.googleapis.com')
```

But if CAI is enabled, storage bucket info is coming from CAI instead, we need to update to make sure for resources that we support w/ CAI doesn't depend only on the enablement of google api for that resource.

**Comment by katze120** [comment]
hi @joecheuk , adding further analysis here:

There are 3 iterator classes or function in ./google/cloud/forseti/services/inventory/base/resources.py that validates enablement of API in target projects:
- compute_iter_class_factory - this is fair because compute.googleapis.com has to be enabled for the project to have compute engine instances.
- KubernetesClusterIterator - similar reason as above
- StorageBucketIterator - IMO resource_validation_method_name='storage_api_enabled' here can be removed because if the project is created by infra-as-code (e.g. terraform), Cloud Storage API (storage-component.googleapis.com) is not by default enabled, and storage buckets can be created via cloud console or terraform without this API being enabled. (However Cloud Storage API is by default enabled when project is created on cloud console and this is probably why this wasn't discussed earlier)

And we also do not need to validate CAI API enablement in these iterators because these iterators are called after CAI raw data is collected. Even for other resources that are not supported by CAI and need to be collected by respective resource APIs, we should validate API enablement in the Forseti project instead of in the target project scanned by Forseti.

Does this make sense? If so I can work on the PR to remove resource_validation_method_name from StorageBucketIterator class in ./google/cloud/forseti/services/inventory/base/resources.py .

```
class StorageBucketIterator(resource_iter_class_factory(
        api_method_name='iter_storage_buckets',
        resource_name='storage_bucket',
        api_method_arg_key='projectNumber',
        resource_validation_method_name='storage_api_enabled')):
    """The Resource iterator implementation for Storage Bucket."""
```
