### ISSUE TITLE
It would be very useful to have root_resource_id as part of forseti-alert Inventory Summay email

### ISSUE THREAD

**Issue by manojawapv-biarca** [forseti-security/forseti-security#2974]
Hello,

I am using Forseti 2.16. I configured forseti to monitor all the projects in my organization. Not all projects need to be scanned every time. Some times I change the root_resource_id and scan only one project. After the scan I get forseti-alert notification email with inventory index. This email does not have the root_resource_id. Now, at a later point of time, if I check the forseti notification emails, I am confused as to on which project/folder/organization the scan was executed on. So, I request for a very small feature addition, which is to add the root_resource_id as part of the forseti-alert notification email, so that it is very useful.

Please let me know if you need any clarifications.

Thanks & Regards,
Manoj

**Comment by blueandgold** [comment]
Hi Manoj, thanks for you feedback. This sounds like a great idea.  The change is not too difficult.  Is this something that you are wiling to contribute?  We can definitely help you to get setup and other pointers. Otherwise, let me added it our sprint planning.

And just to confirm, what you want is the `root_resource_id` from the `forseti_conf_server.yaml` like in this screenshot?

![image](https://user-images.githubusercontent.com/6977544/61230264-8ffa3200-a6de-11e9-87e5-b4c87f184179.png)
