### ISSUE TITLE
Start both CAI data and GCP resource API inventory (e.g. GSuite) as soon as inventory process starts.

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3088]
When the inventory process starts we should start both the collection of data from CAI and any GCP Resources APIs (e.g. GSuite). We should not wait for CAI exports to complete before we start the collection of GSuite data.

**Comment by gkowalski-google** [comment]
@joecheuk @hshin-g Do you know if this has been completed as part of the Inventory optimization efforts?

**Comment by gkowalski-google** [comment]
@hshin-g Please update ticket with reasoning for why this should not be implemented and close out.

**Comment by hshin-g** [comment]
The CAI export does not take a significant amount of time to be downloaded, and calling the GCP APIs happens around the same time as parsing through the CAI resources. There would not be that much of a difference in time by kicking off these processes at the same time, since they happen pretty close together currently. Calling the GCP API is also limited by the number of queries per second that the API can be called, so increasing the number of threads would not be effective, as they are rate limited.
