### ISSUE TITLE
Support concurrent running of Forseti inventory/scan/notification on single Forseti-server instance

### ISSUE THREAD

**Issue by hanan-herz** [forseti-security/forseti-security#3283]
### Make Forseti Stateless Again   (?)
I would like to be able to run Forseti inventory/scan/notification concurrently against different config+rule sets. This is currently not possible with the long-lived Forseti process which has some global locks.

It would be great if Forseti supported in an easy a method to point to a config path and a rules path, run and exit. Forseti 1.x+ was not long-running and supported this a little better.

At the moment, my approach is to run dockerized Forseti instances to support concurrently running against different config+rules files.

Happy to add more details, use-cases, etc.

**Comment by gkowalski-google** [comment]
@hshin-g Please review and see if this is something we should support.

**Comment by blueandgold** [comment]
Copying over the slack thread for context:

henry (google)  8 days ago
@Hanan Herzog Here is another idea.  The Forseti server accepts a a --config_file_path flag, which can be pointed to any forseti_conf_server.yaml, even multiple copies.

henry (google)  8 days ago
https://github.com/forseti-security/forseti-security/blob/master/google/cloud/forseti/services/server.py#L166-L168

google/cloud/forseti/services/server.py:166-168
    parser.add_argument(
        '--config_file_path',
        help='Path to Forseti configuration file.')
<https://github.com/forseti-security/forseti-security|forseti-security/forseti-security>forseti-security/forseti-security | Added by GitHub

henry (google)  8 days ago
this suggests that you can use this to point to the multiple copies of the config/rule files that you may have

henry (google)  8 days ago
I would say that you add your own shell script

henry (google)  8 days ago
.....that can modify how forseti is run, shutdown, and restarted again with the different values for the --config_file_path

henry (google)  8 days ago
and we can add hooks to the terraform deployment, that will allow you to invoke your own custom script

henry (google)  8 days ago
that can be triggered after the normal deployment is done

henry (google)  8 days ago
....how do you think about this?  @Hanan Herzog

Hanan Herzog  7 days ago
Hi @henry (google). Thanks for pointing this out. I wasn't aware of this flag until digging deeper in the last week. It helps but it doesn't address all my issues because then I have to make sure that different instances of Forseti are not run concurrently, because of binding to port 50051 for example.
I really want to run Forseti inventory, scan, and notify in one go concurrently for different configs (or at least in a un-coordinated manner). The reason I want this is to be able to manage the Forseti rules in gitlab and then push changes through some sort of CICD pipeline (much easier to coordinate and track edits that way in my group, very large org).
I am going to continue using the Dockerized forseti for my work, so I will stay away from Terraform updates of Forseti if I can. It's easier to update also.
I guess I still don't understand the value of having Forseti be a client/server--I feel that it creates more limitations than opportunities (compared to the previous single process model). Could this perhaps be revived with some additional options to the entrypoint such that it can take a configfile path (and seperately a rules path), and a command (e.g. inventory,scan,notify or all) to execute and exit? I also think this simpler model would make it more attractive to adopters since it's a simpler "architecture". Happy to discuss somewhere else too.
Very much appreciate your assistance on this. (edited)

**Comment by hshin-g** [comment]
@hanan-u Would you be able to talk through your use cases and workflow a bit more? Would be good to get context on how this is all used, as running multiple Forseti instances concurrently might not be very efficient or fast for our larger users. Our work on getting Forseti onto the microservices architecture could be useful here, and this is something that we can consider once we get there.

**Comment by hanan-herz** [comment]
@hshin-g Happy to explain the background. I'm also extremely open to suggestions on other ways to approach this. Happy to discuss more in another forum and/or in real-time.


The issues with the current Forseti (deployment) architecture are related to managing configurations/rules for a large number of GCP projects, each with potentially **distinct** rules.

**Let's look at IAM rules scanning as a concrete example where the issue was most acute for my org**

1.  IAM rules files would grow to unmanageable size if they included the IAM rules for a large number of individual projects.
   1.1. A typo in one rules causes the scanner to fail entirely, causing all rules to not "work" now
   1.2 Just very difficult to deal deal with huge rules files
3. It is not straight-forward at all to _delegate_ maintenance of specific GCP project's IAM to different departments without some complicated merging strategy into a single rules file
4. It is not possible to scan different projects on different schedules
5. Difficult to experiment with different version of Froseti for "monitoring" different GCP projects 

**What I wound up using the following to achieve a flexible Forseti situation**


1. Using Gitlab + CICD
  1.1 Store, edit config/rules files for specific GCP projects 
  1.2 Push config/rules changes to GCS locations specific to a single Forseti k8s deployment (usually named 
        after the GCP project it is monitoring)
2. My own docker image which is based on the official Forseti Docker image
  2.2 Start forseti_server, run    inventory, scan, notify and **exit**  
3.  Kubernetes to manage distinct "instances" of Forseti, each with distinct config/rules trees
4. Kubernetes cronjob scheduling (which no can be GCP-project specific)

**Background on my org**

My org is quite large (>10K employees) and with a growing set of GCP projects that handle highly confidential information, mainly PHI (medical data). By "**large**", I mean our org's inventory takes over 90 minutes to complete. Separately, gathering data from GSuite for external group access monitoring requires over 24 hours.

Structurally the org is also highly distributed, with a top-level ISO (information security officer) and several security groups underneath, several devops/system-engineering groups and many different departments deployment on their own GCP projects. 

My direct role is as a engineer in one of one of the security groups. I've been using Forseti for two things:
1. Monitor **all** the GCP projects "under" my security group for deviations from recommended security guidelines we have. This one is ok with Forseti as it is today.
2. Monitor **specific** GCP projects with very specific rules including IAM, firewall, BigQuery for specific projects which contain PHI (medical data). This is not easy at all!

**Comment by hanan-herz** [comment]
As a "bonus" of the Kubernetes deployment of Forseti that I am doing is that upgrading Forseti (being as rapidly evolving as it is) is a breeze!
Additionally, for each Forseti job execution I create a new MySQL "database" (not server) on the long-running  cloud-mysql  server-instance we have. This allows me to upgrade and even rollback Forseti versions without schema migration steps. I'm happy with running a new inventory every time I want to scan/notify (which I suspect is what most  people do, as well.)

**Comment by kevensen** [comment]
@hanan-herz I appreciate the detail in your use case.  We will keep this in consideration as we prioritize our next set of feature enhancements.
