### ISSUE TITLE
Update docs - new github structure

### ISSUE THREAD

**Issue by MartenvanWezel** [forseti-security/forseti-security#3513]
https://forsetisecurity.org/docs/latest/configure/scanner/descriptions.html -> yaml files, e.g. ke_rules.yaml gets a 404.

**Comment by gkowalski-google** [comment]
Hi @MartenvanWezel, thanks for submitting the issue. We moved the sample rules out of the rules directory since they are not used when deploying from Terraform and wanted to avoid confusion. These links have been fixed within a dev branch, but this has not been published yet. I just sumitted this [PR](https://github.com/forseti-security/forseti-security/pull/3515) to get these changes into "master" and will deploy this latest version shortly.

**Comment by gkowalski-google** [comment]
This has been resolved and will get published with the v2.25.0 release.
