### ISSUE TITLE
Rules in GCS causes scanner to not run

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3558]
Forseti 2.25?

If a rule path is to a file in GCS, the scanner_builder will not return the scanner, thus the scanner will not run.

https://github.com/forseti-security/forseti-security/blob/e05949567b4c3869e66c32863ebe7aaa28acd55b/google/cloud/forseti/scanner/scanner_builder.py#L127-L130

**Comment by joecheuk** [comment]
This check was added 26 days ago in this PR: https://github.com/forseti-security/forseti-security/commit/42d6d738473e872414951ab9bc85703f1f992aa5#diff-b3ab31b8737b069d164ab56066436a0b

@gkowalski-google is there any reason the check is needed?

**Comment by kevensen** [comment]
@gkowalski-google @joecheuk I'll work on a fix this morning.

**Comment by gkowalski-google** [comment]
@kevensen @joecheuk This issue has already been resolved as part of the v2.25.0 release: https://github.com/forseti-security/forseti-security/pull/3541; it was merged into the release branch. This check was added as part of moving the sample rules out of the rules directory. The Config Validator scanner does not have a rule file. For the other scanners, if the rules file is not present then the scanner will not build successfully. I put this check in to make it more obvious what the issue is.
