### ISSUE TITLE
UnknownApiNameOrVersion: cloudbilling & serviceusage

### ISSUE THREAD

**Issue by gkowalski-google** [forseti-security/forseti-security#3748]
## Story
[Recently an issue was resolved](https://github.com/forseti-security/forseti-security/pull/3743) where the google api client was throwing an error, and not it appears the same issue is happening to the cloudbilling and serviceusage clients.

Error in the server VM logs can be found similar to:
```
googleapiclient.errors.UnknownApiNameOrVersion: name: cloudbilling  version: v1
```

## Workaround
Disable the CloudBilling and ServiceUsage API polling within the Terraform config to allow inventory to complete, however it might cause issues with scanning.
```
cloudbilling_disable_polling    = true
serviceusage_disable_polling    = true
```

**Comment by rajcheval** [comment]
@gkowalski-google  we were finally able to get to the bottom of this issue. It is not a bug.
We were using restricted api's. Since cloudbilling and serviceusage were not supported by VPC SC the calls to these API's were blocked. Once we switched to private API's we were able to enable cloudbilling and serviceusage polling.
