### ISSUE TITLE
Add a validate_config() util method.

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#424]
Now that we have a lot of configs moved to the config file, it would be nice to safeguard against bad configs being set and then used.  One idea is to have a centralized validate_configs() util method that would used when or after reading the configs.

**Comment by carise** [comment]
Some ideas for handling application configurations:

https://hackernoon.com/4-ways-to-manage-the-configuration-in-python-4623049e841b
http://flask.pocoo.org/docs/0.12/config/
https://stackoverflow.com/questions/6198372/most-pythonic-way-to-provide-global-configuration-variables-in-config-py

Instead of checking configs in the code wherever it's needed, create a config module that checks config validity. Also, if configs are marked deprecated (could probably make "deprecated: true" a property of each config directive), show a LOGGER.warning().
