### ISSUE TITLE
Automate Signed releases

### ISSUE THREAD

**Issue by daenney** [forseti-security/forseti-security#653]
The currently published releases are just GitHub providing bundles for the tags. However, this means no hash is published allowing for more easily validating the bundle and means the releases aren't signed.

It would be great if you could leverage GitHub's support for signed releases so anyone has the opportunity to validate the release before executing any of the associated code. As far as I'm aware Travis can be leveraged to do this, by encrypting (`travis encrypt`) a GPG signing key into the repository (or some other location Travis can fetch from) and using that to sign the release. This would require [packaging an actual release](https://docs.travis-ci.com/user/deployment/releases/) though, which Travis supports, and not purely relying on the tag to bundle trick GitHub applies. Letting Travis decrypt and use that key could be a concern though but then it seems this would have to be a manual step.

**Comment by dekuhn** [comment]
Cleanup of old issues. Please re-open if there's still interest.

**Comment by daenney** [comment]
Please re-open. This is a security product. It ought to come with signed release that I can verify before deploying it.

**Comment by dekuhn** [comment]
@blueandgold Henry this issue has sat since 2017. If is important to the project please triage and outline the eng effort needed for this. I took some time to link to a few details that should help us size this effort.

This is a good primer: https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe

- [ ] Goal: Sign tag and released binaries
- [ ] Establish a PGP signing key (Need to define key lifetime)
- [ ] Backup PGP keys in secure system - public key, private key and revocation certificate

Update Travis build pipeline to sign tagged / binary releases with PGP key
Good primer for storing encrypted key in Travis: https://gist.github.com/kzap/5819745
- [ ] Encrypt private key and store in GitHub
- [ ] Store decryption key for pgp key in secure Travis encrypted variable
- [ ] Update Travis build to decrypt pgp key using secure variable to  private key
- [ ] Add signing steps to Travis to sign tagged builds
- [ ] Add signing steps to Travus to sign released binary files

**Comment by blueandgold** [comment]
@daenney, as a starter, we can add the release signing step for the release engineer to do, as part of our release process. We can start to do this for our next 2.17 release.

An example process of how to sign a release manually is here:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by Red-Five** [comment]
@kevensen We should consider 'signed' Docker images.

**Comment by dekuhn** [comment]
Release [v2.17](https://github.com/forseti-security/forseti-security/releases) is our first signed release.

This is a great first step. Next steps is we need to work on having the automated build pipeline do this for us.

**Comment by daenney** [comment]
This is great, thank you! Is the GPG key documented somewhere so I can validate the signature?

**Comment by dekuhn** [comment]
@blueandgold can you followup how the key can be verified?

**Comment by gkowalski-google** [comment]
We don't plan on automating the signed releases at this time, we will use this to:

- can we publish a hash that users can use to verify the release?
- are the Forseti images signed?

**Comment by kevensen** [comment]
The Forseti images are not signed.  At this point in time, GCR doesn't support signed images.

**Comment by dekuhn** [comment]
We have decided to continue our manual release signing process for releases and not focus resources on automation for release signing at this time.
