### ISSUE TITLE
Support BigQuery as Storage

### ISSUE THREAD

**Issue by blueandgold** [forseti-security/forseti-security#662]
Multiple users have asked about using BigQuery as storage, instead of maintaining a mysql instance.  Inventory v2 should make this possible when storage is allowed to be pluggable.

**Comment by radkomateusz** [comment]
Hello, 

We are thinking about a little different approach - automatic export of all mysql tables to BigQuery (rather as a backup, not instead of mysql). It would allow us to have historical data of our inventory and violations in BigQuery, even after reinstall forseti (cleanining/destroying mysql instance, maybe if schema changes in new version etc.).

**Comment by blueandgold** [comment]
This sounds like a great idea!  Would this be something that you would be willing to look into, and contribute?

**Comment by radkomateusz** [comment]
In general yes, we want to look into this issue, but probably not in the nearest 2 weeks.
