### ISSUE TITLE
Setup fails to detect Org Admin role when Org Admin is a Google Group

### ISSUE THREAD

**Issue by xsgbloom** [forseti-security/forseti-security#780]
Found in version 1.1.7

When setup_forseti.py is run, it attempts to detect whether the user running setup is an Org Admin. If the user has been granted the Org Admin role by virtue of being a member of a Group that was assigned the Org Admin role, the script reports that the user isn't an Org Admin and fails.

I suspect this is the case because Forseti is looking for a match with the list of all users in the Org Admin list and isn't able to expand the members of any groups. Instead, maybe the setup script should test for Org Admin capabilities.

**Comment by carise** [comment]
You can get around the org admin check by using the --no-iam-check flag on the setup_forseti.py script.

**Comment by carise** [comment]
related: #694

**Comment by mirons-google** [comment]
Thanks for opening the issue @xsgbloom.

How best can we surface the capability @carise mentioned? Would this be a FAQ and/or in-line in the installation guide?

**Comment by blueandgold** [comment]
Perhaps the setup wizard can output a message to prompt the user to use the flag, if the user is part of an org admin google group?

**Comment by carise** [comment]
Additional thoughts -- gcloud does not know about G Suite groups/members. If we wanted to do full group expansion, we'd actually need to use the Admin SDK (i.e. basically, we'd have to use Forseti or IAM Explain to disambiguate the current user's effective IAM permissions and set up Forseti...). I'd like to keep the dependencies small for setup, otherwise we are creating more hurdles for the installation.
